<template>
  <div class="full" @click="reload()">
    <h1 class="job-title">{{ serie }}</h1>
  </div>
</template>

<script>

export default {
  name: 'Game',
  components: { },
  data() {
    return {
      series: [
        "Juego de Tronos",
        "Breaking Bad",
        "Stranger Things",
        "The Crown",
        "Black Mirror",
        "Friends",
        "The Office",
        "Sherlock",
        "Narcos",
        "La Casa de Papel",
        "The Mandalorian",
        "The Witcher",
        "Chernobyl",
        "Vikingos",
        "Mindhunter",
        "Westworld",
        "The Walking Dead",
        "Fleabag",
        "El Cuento de la Criada",
        "Peaky Blinders",
        "Better Call Saul",
        "Élite",
        "Dark",
        "The Big Bang Theory",
        "Stranger Things",
        "La Maldición de Hill House",
        "BoJack Horseman",
        "Daredevil",
        "The Punisher",
        "Narcos: México",
        "GLOW",
        "Ozark",
        "The Handmaid's Tale",
        "Money Heist",
        "Narcos",
        "Sense8",
        "Vikings",
        "The Marvelous Mrs. Maisel",
        "The Umbrella Academy",
        "La Casa de las Flores",
        "Black Mirror",
        "The Boys",
        "Fargo",
        "The Mandalorian",
        "The Witcher",
        "Breaking Bad",
        "Mr. Robot",
        "La Casa de Papel",
        "The Crown",
        "Fleabag",
        "Westworld",
        "The Walking Dead",
        "Stranger Things",
        "Dark",
        "Friends",
        "The Big Bang Theory",
        "How I Met Your Mother",
        "Los Soprano",
        "The Wire",
        "Lost",
        "Dexter",
        "The Simpsons",
        "Modern Family",
        "The Office",
        "Parks and Recreation",
        "Brooklyn Nine-Nine",
        "The Good Place",
        "Stranger Things",
        "Black Mirror",
        "Narcos",
        "La Casa de Papel",
        "The Witcher",
        "Élite",
        "Dark",
        "Vikings",
        "Mindhunter",
        "The Mandalorian",
        "Breaking Bad",
        "Friends",
        "The Office",
        "Sherlock",
        "The Crown",
        "Fleabag",
        "Peaky Blinders",
        "Better Call Saul",
        "Money Heist",
        "The Handmaid's Tale",
        "The Umbrella Academy",
        "The Boys",
        "Fargo",
        "La Casa de las Flores",
        "Black Mirror",
        "The Witcher",
        "Stranger Things",
        "Dark",
        "Breaking Bad",
        "The Mandalorian",
        "Vikings",
        "Narcos",
        "Friends",
        "The Office",
        "La Casa de Papel",
        "Élite",
        "Mindhunter",
        "Westworld",
        "The Crown",
        "Fleabag",
        "Peaky Blinders",
        "Better Call Saul",
        "Money Heist",
        "The Witcher",
        "The Boys",
        "Fargo",
        "The Umbrella Academy",
        "Black Mirror",
        "Stranger Things",
        "Dark",
        "Breaking Bad",
        "The Mandalorian",
        "Vikings",
        "Narcos",
        "Friends",
        "The Office",
        "La Casa de Papel",
        "Élite",
        "Mindhunter",
        "Westworld",
        "The Crown",
        "Fleabag",
        "Peaky Blinders",
        "Better Call Saul",
        "Money Heist",
        "The Witcher",
        "The Boys",
        "Fargo",
        "The Umbrella Academy",
        "Black Mirror"
      ],
      serie: "",
      movies: [
        "Titanic",
        "El Padrino",
        "Cadena perpetua",
        "Forrest Gump",
        "El señor de los anillos: El retorno del rey",
        "El caballero de la noche",
        "Matrix",
        "Star Wars: Episodio IV - Una nueva esperanza",
        "E.T. el extraterrestre",
        "Jurassic Park",
        "Avatar",
        "El rey león",
        "Gladiador",
        "Casablanca",
        "La La Land",
        "Pulp Fiction",
        "Harry Potter",
        "Interestelar",
        "El club de la pelea",
        "Ratatouille",
        "El discurso del rey",
        "El resplandor",
        "Frozen",
        "El Rey León (1994)",
        "La Bella y la Bestia",
        "Toy Story",
        "La Sirenita",
        "Aladdin",
        "Cenicienta",
        "Blancanieves y los siete enanitos",
        "El Libro de la Selva",
        "La Cenicienta (2015)",
        "La Dama y el Vagabundo",
        "Moana",
        "Mulán",
        "Zootopia",
        "El Jorobado de Notre Dame",
        "Buscando a Nemo",
        "Los Increíbles",
        "La Princesa Prometida",
        "Los Goonies",
        "El Rey León (2019)",
        "La La Land",
        "Ratatouille",
        "Toy Story",
        "La Sirenita",
        "Aladdin",
        "La Bella y la Bestia",
        "Cenicienta",
        "Blancanieves y los siete enanitos",
        "El Libro de la Selva",
        "La Dama y el Vagabundo",
        "Buscando a Nemo",
        "Zootopia",
        "Frozen",
        "Moana",
        "Mulán",
        "El Jorobado de Notre Dame",
        "Los Increíbles",
        "Up",
        "Wall-E",
        "Inside Out",
        "Coco",
        "Enredados",
        "Ralph, el demoledor",
        "Mi Vecino Totoro",
        "El Viaje de Chihiro",
        "El Castillo en el Cielo",
        "La Fiesta de las Salchichas",
        "Shrek",
        "Madagascar",
        "Los Croods",
        "Cómo Entrenar a tu Dragón",
        "Monsters, Inc.",
        "Cars",
        "Buscando a Dory",
        "Kung Fu Panda",
        "Mi Villano Favorito",
        "Coraline",
        "El Principito",
        "Paddington",
        "La Invención de Hugo",
        "El Expreso Polar",
        "El Grinch"
      ]
    }
  },
  async mounted() {
    this.reload()
  },

  methods: {
    reload() {
      const min = 0
      const max = this.movies.length - 1
      this.serie = this.movies[Math.floor(Math.random() * (max - min + 1)) + min]
    }
  }
}
</script>

<style scoped>
h1, h2 {
  font-weight: normal;
}


.job-title {
  padding: 2rem 0;
  font-size: 50px;
  letter-spacing: 1rem;
}

.full{
  height: 100vh;
  -webkit-transform: rotate(-90deg);
  -moz-transform: rotate(-80deg);
  -o-transform: rotate(-80deg);
  display: flex;
  justify-content: center;
  align-items: center;
}

</style>

